/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile */
        get: operations["getById"];
        /** Update user profile */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark a notification as read */
        put: operations["markRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Return a borrowed book */
        put: operations["returnBook"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a venue */
        put: operations["updateVenue"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/sessions/{id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark a learner present/absent for a session */
        put: operations["markAttendance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a course's full syllabus for editing, any status */
        get: operations["getById_2"];
        /** Update a course's fields */
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/courses/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Revert a course to draft */
        put: operations["unpublish"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/courses/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Publish a course, making it visible to learners */
        put: operations["publish"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/batches/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Publish a batch, opening it for booking */
        put: operations["publishBatch"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/batches/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cancel a batch */
        put: operations["cancelBatch"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a book */
        put: operations["update_2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe to a plan */
        post: operations["subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's orders */
        get: operations["getUserOrders"];
        put?: never;
        /** Create an order */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's loans */
        get: operations["getUserLoans"];
        put?: never;
        /** Borrow a book */
        post: operations["borrow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/tests/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new attempt at a test */
        post: operations["startAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/lessons/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a lesson complete for the current user */
        post: operations["completeLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/courses/{id}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll in a course; paid courses require a PaymentInput body */
        post: operations["enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/batches/{id}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book a seat in a batch (waitlisted automatically once full); paid batches require a PaymentInput body */
        post: operations["bookSeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/attempts/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit answers for an attempt and get the scored result */
        post: operations["submitAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token and mint a new access token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout: revoke the refresh-token family and clear the cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and get tokens */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all venues */
        get: operations["listVenues"];
        put?: never;
        /** Create a venue */
        post: operations["createVenue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/tests/{id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a question (with its options) to a test */
        post: operations["addQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/modules/{moduleId}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a lesson to a module */
        post: operations["addLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all courses, any status */
        get: operations["list_5"];
        put?: never;
        /** Create a draft course */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/courses/{id}/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a course's tests, with question counts */
        get: operations["listTests_1"];
        put?: never;
        /** Create a test for a course */
        post: operations["createTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/courses/{id}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a module to a course */
        post: operations["addModule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/courses/{id}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a course's in-person batches, with roster counts */
        get: operations["listBatches_1"];
        put?: never;
        /** Schedule a batch (with its sessions) for a course */
        post: operations["createBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new book */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available subscription plans */
        get: operations["getPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user subscription */
        get: operations["getCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's notifications, newest first */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread notification count, for the navbar bell badge */
        get: operations["unreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/tests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a test's questions for taking it (no answer key) */
        get: operations["getTest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/me/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's course enrollments */
        get: operations["myEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/me/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's earned certificates */
        get: operations["myCertificates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/me/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's batch bookings */
        get: operations["myBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse published courses with optional filters */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published course's full syllabus by slug */
        get: operations["getBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/courses/{id}/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List this course's tests with the current user's attempt status */
        get: operations["listTests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/courses/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's lesson-completion progress for an enrolled course */
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/courses/{id}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a course's upcoming published in-person batches */
        get: operations["listBatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/certificates/{serial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Publicly verify a certificate by its serial */
        get: operations["verifyCertificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all books with optional filters */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a book by ID */
        get: operations["getById_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all members with plan and active-loan counts */
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all loans, optionally filtered by status (active/overdue/returned) */
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/tests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a test's full question bank, including the answer key */
        get: operations["getTest_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a batch's sessions and full roster */
        get: operations["getBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learn/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enrollment/completion/revenue/attendance aggregates across all courses */
        get: operations["getAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learn/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a booking (promotes the next waitlisted learner if this seat was confirmed) */
        delete: operations["cancelBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserRequest: {
            firstName?: string;
            lastName?: string;
            phone?: string;
            address?: string;
        };
        ApiResponseUserResponse: {
            success?: boolean;
            data?: components["schemas"]["UserResponse"];
            message?: string;
            error?: string;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            name?: string;
            role?: string;
            phone?: string;
            address?: string;
        };
        ApiResponseNotificationResponse: {
            success?: boolean;
            data?: components["schemas"]["NotificationResponse"];
            message?: string;
            error?: string;
        };
        NotificationResponse: {
            /** Format: uuid */
            id?: string;
            type?: string;
            title?: string;
            body?: string;
            read?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseLoanResponse: {
            success?: boolean;
            data?: components["schemas"]["LoanResponse"];
            message?: string;
            error?: string;
        };
        LoanResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            bookId?: string;
            bookTitle?: string;
            bookAuthor?: string;
            bookCover?: string;
            /** Format: date-time */
            borrowedAt?: string;
            /** Format: date-time */
            dueDate?: string;
            /** Format: date-time */
            returnedAt?: string;
            status?: string;
        };
        VenueRequest: {
            name: string;
            address?: string;
            city: string;
            /** Format: int32 */
            capacityDefault?: number;
        };
        ApiResponseVenueResponse: {
            success?: boolean;
            data?: components["schemas"]["VenueResponse"];
            message?: string;
            error?: string;
        };
        VenueResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            address?: string;
            city?: string;
            /** Format: int32 */
            capacityDefault?: number;
        };
        AttendanceInput: {
            /** Format: uuid */
            userId: string;
            present?: boolean;
        };
        ApiResponseVoid: {
            success?: boolean;
            data?: Record<string, never>;
            message?: string;
            error?: string;
        };
        CourseRequest: {
            slug: string;
            title: string;
            /** @enum {string} */
            track: "MONEY_FOUNDATIONS" | "EQUITIES" | "BONDS_FIXED_INCOME" | "DERIVATIVES" | "PORTFOLIO_RISK";
            /** @enum {string} */
            level: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
            language: string;
            summary?: string;
            price: number;
        };
        ApiResponseCourseSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["CourseSummaryResponse"];
            message?: string;
            error?: string;
        };
        CourseSummaryResponse: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            title?: string;
            track?: string;
            level?: string;
            language?: string;
            summary?: string;
            price?: number;
            status?: string;
            /** Format: int32 */
            moduleCount?: number;
            /** Format: int64 */
            lessonCount?: number;
        };
        AdminBatchSummaryResponse: {
            /** Format: uuid */
            id?: string;
            venueName?: string;
            instructorName?: string;
            /** Format: date */
            startsOn?: string;
            /** Format: date */
            endsOn?: string;
            scheduleText?: string;
            /** Format: int32 */
            capacity?: number;
            fee?: number;
            status?: string;
            /** Format: int64 */
            confirmedCount?: number;
            /** Format: int64 */
            waitlistedCount?: number;
        };
        ApiResponseAdminBatchSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminBatchSummaryResponse"];
            message?: string;
            error?: string;
        };
        BookRequest: {
            title: string;
            author: string;
            isbn: string;
            description?: string;
            /** Format: int32 */
            totalCopies?: number;
            purchasePrice: number;
            category?: string;
            language?: string;
            /** Format: int32 */
            pageCount?: number;
            /** Format: double */
            rating?: number;
            coverUrl?: string;
            /** Format: int32 */
            publishedYear?: number;
        };
        ApiResponseBookResponse: {
            success?: boolean;
            data?: components["schemas"]["BookResponse"];
            message?: string;
            error?: string;
        };
        BookResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            author?: string;
            isbn?: string;
            description?: string;
            /** Format: int32 */
            totalCopies?: number;
            /** Format: int32 */
            availableCopies?: number;
            available?: boolean;
            purchasePrice?: number;
            category?: string;
            genre?: string;
            language?: string;
            /** Format: int32 */
            pageCount?: number;
            /** Format: double */
            rating?: number;
            cover?: string;
            /** Format: int32 */
            publishedYear?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        SubscriptionRequest: {
            /** @enum {string} */
            plan: "BASIC" | "PREMIUM" | "ADMIN";
        };
        ApiResponseSubscriptionResponse: {
            success?: boolean;
            data?: components["schemas"]["SubscriptionResponse"];
            message?: string;
            error?: string;
        };
        SubscriptionResponse: {
            /** Format: uuid */
            id?: string;
            plan?: string;
            monthlyPrice?: number;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            status?: string;
            /** Format: int32 */
            maxConcurrentLoans?: number;
        };
        OrderRequest: {
            totalAmount: number;
            notes?: string;
        };
        ApiResponseOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["OrderResponse"];
            message?: string;
            error?: string;
        };
        OrderResponse: {
            /** Format: uuid */
            id?: string;
            totalAmount?: number;
            status?: string;
            notes?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        LoanRequest: {
            /** Format: uuid */
            bookId: string;
            /** Format: int32 */
            daysToKeep?: number;
        };
        ApiResponseAttemptStartResponse: {
            success?: boolean;
            data?: components["schemas"]["AttemptStartResponse"];
            message?: string;
            error?: string;
        };
        AttemptStartResponse: {
            /** Format: uuid */
            attemptId?: string;
            /** Format: uuid */
            testId?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: int32 */
            timeLimitMin?: number;
        };
        ApiResponseCourseProgressResponse: {
            success?: boolean;
            data?: components["schemas"]["CourseProgressResponse"];
            message?: string;
            error?: string;
        };
        CourseProgressResponse: {
            /** Format: uuid */
            courseId?: string;
            /** Format: int64 */
            totalLessons?: number;
            /** Format: int64 */
            completedLessons?: number;
            completedLessonIds?: string[];
            /** Format: uuid */
            nextLessonId?: string;
        };
        PaymentInput: {
            cardholderName?: string;
            cardNumber?: string;
            expiryMonth?: string;
            expiryYear?: string;
            cvc?: string;
        };
        ApiResponseEnrollmentResponse: {
            success?: boolean;
            data?: components["schemas"]["EnrollmentResponse"];
            message?: string;
            error?: string;
        };
        EnrollmentResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            courseId?: string;
            courseSlug?: string;
            courseTitle?: string;
            status?: string;
            /** Format: date-time */
            enrolledAt?: string;
            /** Format: int64 */
            totalLessons?: number;
            /** Format: int64 */
            completedLessons?: number;
            /** Format: uuid */
            nextLessonId?: string;
            amountPaid?: number;
        };
        ApiResponseBookingResponse: {
            success?: boolean;
            data?: components["schemas"]["BookingResponse"];
            message?: string;
            error?: string;
        };
        BookingResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            batchId?: string;
            courseTitle?: string;
            venueName?: string;
            /** Format: date */
            startsOn?: string;
            /** Format: date */
            endsOn?: string;
            status?: string;
            /** Format: date-time */
            bookedAt?: string;
            amountPaid?: number;
        };
        AnswerInput: {
            /** Format: uuid */
            questionId: string;
            selectedOptionIds?: string[];
        };
        AttemptSubmitRequest: {
            answers: components["schemas"]["AnswerInput"][];
        };
        ApiResponseAttemptResultResponse: {
            success?: boolean;
            data?: components["schemas"]["AttemptResultResponse"];
            message?: string;
            error?: string;
        };
        AttemptResultResponse: {
            /** Format: uuid */
            attemptId?: string;
            /** Format: int32 */
            scorePercent?: number;
            passed?: boolean;
            /** Format: int32 */
            attemptsUsed?: number;
            /** Format: int32 */
            attemptsAllowed?: number;
            certificateIssued?: boolean;
            certificateSerial?: string;
            questionResults?: components["schemas"]["QuestionResultResponse"][];
        };
        QuestionResultResponse: {
            /** Format: uuid */
            questionId?: string;
            correct?: boolean;
            correctOptionIds?: string[];
            selectedOptionIds?: string[];
        };
        RegisterRequest: {
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            phone?: string;
            address?: string;
        };
        ApiResponseAuthResponse: {
            success?: boolean;
            data?: components["schemas"]["AuthResponse"];
            message?: string;
            error?: string;
        };
        AuthResponse: {
            /** Format: uuid */
            userId?: string;
            email?: string;
            name?: string;
            role?: string;
            plan?: string;
            accessToken?: string;
            refreshToken?: string;
        };
        RefreshRequest: {
            refreshToken?: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        QuestionOptionInput: {
            label: string;
            correct?: boolean;
        };
        QuestionRequest: {
            prompt: string;
            /** @enum {string} */
            kind: "SINGLE" | "MULTI" | "TRUEFALSE";
            options: components["schemas"]["QuestionOptionInput"][];
        };
        AdminOptionResponse: {
            /** Format: uuid */
            id?: string;
            label?: string;
            correct?: boolean;
            /** Format: int32 */
            sortOrder?: number;
        };
        AdminQuestionResponse: {
            /** Format: uuid */
            id?: string;
            prompt?: string;
            kind?: string;
            /** Format: int32 */
            sortOrder?: number;
            options?: components["schemas"]["AdminOptionResponse"][];
        };
        ApiResponseAdminQuestionResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminQuestionResponse"];
            message?: string;
            error?: string;
        };
        LessonRequest: {
            title: string;
            /** @enum {string} */
            kind: "VIDEO" | "ARTICLE" | "PDF" | "SLIDES";
            contentUrl?: string;
            body?: string;
            /** Format: int32 */
            estMinutes?: number;
        };
        ApiResponseLessonResponse: {
            success?: boolean;
            data?: components["schemas"]["LessonResponse"];
            message?: string;
            error?: string;
        };
        LessonResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            kind?: string;
            contentUrl?: string;
            body?: string;
            /** Format: int32 */
            estMinutes?: number;
            /** Format: int32 */
            sortOrder?: number;
        };
        TestRequest: {
            title: string;
            /** Format: int32 */
            passPercent?: number;
            /** Format: int32 */
            timeLimitMin?: number;
            /** Format: int32 */
            attemptsAllowed?: number;
        };
        AdminTestSummaryResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: int32 */
            passPercent?: number;
            /** Format: int32 */
            timeLimitMin?: number;
            /** Format: int32 */
            attemptsAllowed?: number;
            /** Format: int32 */
            questionCount?: number;
        };
        ApiResponseAdminTestSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminTestSummaryResponse"];
            message?: string;
            error?: string;
        };
        ModuleRequest: {
            title: string;
        };
        ApiResponseModuleResponse: {
            success?: boolean;
            data?: components["schemas"]["ModuleResponse"];
            message?: string;
            error?: string;
        };
        ModuleResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: int32 */
            sortOrder?: number;
            lessons?: components["schemas"]["LessonResponse"][];
        };
        BatchRequest: {
            /** Format: uuid */
            venueId: string;
            instructorName: string;
            /** Format: date */
            startsOn: string;
            /** Format: date */
            endsOn: string;
            scheduleText: string;
            /** Format: int32 */
            capacity?: number;
            fee: number;
            sessions: components["schemas"]["SessionInput"][];
        };
        SessionInput: {
            /** Format: date */
            sessionDate: string;
            topic: string;
        };
        ApiResponseListSubscriptionPlanResponse: {
            success?: boolean;
            data?: components["schemas"]["SubscriptionPlanResponse"][];
            message?: string;
            error?: string;
        };
        SubscriptionPlanResponse: {
            id?: string;
            name?: string;
            price?: number;
            /** Format: int32 */
            maxBooks?: number;
            features?: string[];
            popular?: boolean;
        };
        ApiResponseListOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["OrderResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponseListNotificationResponse: {
            success?: boolean;
            data?: components["schemas"]["NotificationResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponseMapStringLong: {
            success?: boolean;
            data?: {
                [key: string]: number;
            };
            message?: string;
            error?: string;
        };
        ApiResponseListLoanResponse: {
            success?: boolean;
            data?: components["schemas"]["LoanResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponseTestForLearnerResponse: {
            success?: boolean;
            data?: components["schemas"]["TestForLearnerResponse"];
            message?: string;
            error?: string;
        };
        OptionResponse: {
            /** Format: uuid */
            id?: string;
            label?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        QuestionResponse: {
            /** Format: uuid */
            id?: string;
            prompt?: string;
            kind?: string;
            /** Format: int32 */
            sortOrder?: number;
            options?: components["schemas"]["OptionResponse"][];
        };
        TestForLearnerResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: int32 */
            passPercent?: number;
            /** Format: int32 */
            timeLimitMin?: number;
            /** Format: int32 */
            attemptsAllowed?: number;
            /** Format: int32 */
            attemptsUsed?: number;
            questions?: components["schemas"]["QuestionResponse"][];
        };
        ApiResponseListEnrollmentResponse: {
            success?: boolean;
            data?: components["schemas"]["EnrollmentResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponseListCertificateResponse: {
            success?: boolean;
            data?: components["schemas"]["CertificateResponse"][];
            message?: string;
            error?: string;
        };
        CertificateResponse: {
            /** Format: uuid */
            id?: string;
            courseTitle?: string;
            courseSlug?: string;
            /** Format: date-time */
            issuedAt?: string;
            serial?: string;
        };
        ApiResponseListBookingResponse: {
            success?: boolean;
            data?: components["schemas"]["BookingResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponsePagedResponseCourseSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["PagedResponseCourseSummaryResponse"];
            message?: string;
            error?: string;
        };
        PagedResponseCourseSummaryResponse: {
            content?: components["schemas"]["CourseSummaryResponse"][];
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            hasNext?: boolean;
            hasPrev?: boolean;
        };
        ApiResponseCourseDetailResponse: {
            success?: boolean;
            data?: components["schemas"]["CourseDetailResponse"];
            message?: string;
            error?: string;
        };
        CourseDetailResponse: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            title?: string;
            track?: string;
            level?: string;
            language?: string;
            summary?: string;
            price?: number;
            status?: string;
            modules?: components["schemas"]["ModuleResponse"][];
        };
        ApiResponseListTestListItemResponse: {
            success?: boolean;
            data?: components["schemas"]["TestListItemResponse"][];
            message?: string;
            error?: string;
        };
        TestListItemResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: int32 */
            passPercent?: number;
            /** Format: int32 */
            timeLimitMin?: number;
            /** Format: int32 */
            attemptsAllowed?: number;
            /** Format: int32 */
            attemptsUsed?: number;
            /** Format: int32 */
            bestScorePercent?: number;
            passed?: boolean;
        };
        ApiResponseListBatchForLearnerResponse: {
            success?: boolean;
            data?: components["schemas"]["BatchForLearnerResponse"][];
            message?: string;
            error?: string;
        };
        BatchForLearnerResponse: {
            /** Format: uuid */
            id?: string;
            venueName?: string;
            city?: string;
            instructorName?: string;
            /** Format: date */
            startsOn?: string;
            /** Format: date */
            endsOn?: string;
            scheduleText?: string;
            fee?: number;
            /** Format: int32 */
            seatsAvailable?: number;
            myBookingStatus?: string;
        };
        ApiResponseCertificateVerifyResponse: {
            success?: boolean;
            data?: components["schemas"]["CertificateVerifyResponse"];
            message?: string;
            error?: string;
        };
        CertificateVerifyResponse: {
            serial?: string;
            learnerName?: string;
            courseTitle?: string;
            /** Format: date-time */
            issuedAt?: string;
        };
        ApiResponsePagedResponseBookResponse: {
            success?: boolean;
            data?: components["schemas"]["PagedResponseBookResponse"];
            message?: string;
            error?: string;
        };
        PagedResponseBookResponse: {
            content?: components["schemas"]["BookResponse"][];
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            hasNext?: boolean;
            hasPrev?: boolean;
        };
        AdminUserResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            email?: string;
            role?: string;
            active?: boolean;
            plan?: string;
            /** Format: int64 */
            activeLoans?: number;
            /** Format: date-time */
            joinedAt?: string;
        };
        ApiResponseListAdminUserResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminUserResponse"][];
            message?: string;
            error?: string;
        };
        AdminLoanResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            bookId?: string;
            bookTitle?: string;
            memberName?: string;
            memberEmail?: string;
            /** Format: date-time */
            borrowedAt?: string;
            /** Format: date-time */
            dueDate?: string;
            /** Format: date-time */
            returnedAt?: string;
            status?: string;
        };
        ApiResponseListAdminLoanResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminLoanResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponseListVenueResponse: {
            success?: boolean;
            data?: components["schemas"]["VenueResponse"][];
            message?: string;
            error?: string;
        };
        AdminTestDetailResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: int32 */
            passPercent?: number;
            /** Format: int32 */
            timeLimitMin?: number;
            /** Format: int32 */
            attemptsAllowed?: number;
            questions?: components["schemas"]["AdminQuestionResponse"][];
        };
        ApiResponseAdminTestDetailResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminTestDetailResponse"];
            message?: string;
            error?: string;
        };
        ApiResponseListCourseSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["CourseSummaryResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponseListAdminTestSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminTestSummaryResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponseListAdminBatchSummaryResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminBatchSummaryResponse"][];
            message?: string;
            error?: string;
        };
        AdminBatchDetailResponse: {
            /** Format: uuid */
            id?: string;
            venueName?: string;
            instructorName?: string;
            /** Format: date */
            startsOn?: string;
            /** Format: date */
            endsOn?: string;
            scheduleText?: string;
            /** Format: int32 */
            capacity?: number;
            fee?: number;
            status?: string;
            sessions?: components["schemas"]["SessionResponse"][];
            roster?: components["schemas"]["RosterEntryResponse"][];
        };
        ApiResponseAdminBatchDetailResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminBatchDetailResponse"];
            message?: string;
            error?: string;
        };
        RosterEntryResponse: {
            /** Format: uuid */
            bookingId?: string;
            /** Format: uuid */
            userId?: string;
            userName?: string;
            userEmail?: string;
            status?: string;
            /** Format: date-time */
            bookedAt?: string;
        };
        SessionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            sessionDate?: string;
            topic?: string;
        };
        AdminAnalyticsResponse: {
            /** Format: int64 */
            totalEnrollments?: number;
            totalRevenue?: number;
            completionFunnel?: components["schemas"]["CompletionFunnelResponse"];
            enrollmentsByDay?: components["schemas"]["DailyEnrollmentCount"][];
            revenueByCourse?: components["schemas"]["CourseRevenueResponse"][];
            /** Format: double */
            attendanceRatePercent?: number;
        };
        ApiResponseAdminAnalyticsResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminAnalyticsResponse"];
            message?: string;
            error?: string;
        };
        CompletionFunnelResponse: {
            /** Format: int64 */
            enrolled?: number;
            /** Format: int64 */
            startedLesson?: number;
            /** Format: int64 */
            completedAllLessons?: number;
            /** Format: int64 */
            certified?: number;
        };
        CourseRevenueResponse: {
            courseTitle?: string;
            revenue?: number;
        };
        DailyEnrollmentCount: {
            /** Format: date */
            date?: string;
            /** Format: int64 */
            count?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNotificationResponse"];
                };
            };
        };
    };
    returnBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoanResponse"];
                };
            };
        };
    };
    updateVenue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVenueResponse"];
                };
            };
        };
    };
    markAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCourseDetailResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCourseSummaryResponse"];
                };
            };
        };
    };
    unpublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCourseSummaryResponse"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCourseSummaryResponse"];
                };
            };
        };
    };
    publishBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminBatchSummaryResponse"];
                };
            };
        };
    };
    cancelBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminBatchSummaryResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBookResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSubscriptionResponse"];
                };
            };
        };
    };
    getUserOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListOrderResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponse"];
                };
            };
        };
    };
    getUserLoans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListLoanResponse"];
                };
            };
        };
    };
    borrow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoanResponse"];
                };
            };
        };
    };
    startAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptStartResponse"];
                };
            };
        };
    };
    completeLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCourseProgressResponse"];
                };
            };
        };
    };
    enroll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PaymentInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEnrollmentResponse"];
                };
            };
        };
    };
    bookSeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PaymentInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBookingResponse"];
                };
            };
        };
    };
    submitAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptSubmitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptResultResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Type"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Type"?: string;
            };
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Type"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    listVenues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListVenueResponse"];
                };
            };
        };
    };
    createVenue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVenueResponse"];
                };
            };
        };
    };
    addQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminQuestionResponse"];
                };
            };
        };
    };
    addLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLessonResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCourseSummaryResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCourseSummaryResponse"];
                };
            };
        };
    };
    listTests_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAdminTestSummaryResponse"];
                };
            };
        };
    };
    createTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminTestSummaryResponse"];
                };
            };
        };
    };
    addModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseModuleResponse"];
                };
            };
        };
    };
    listBatches_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAdminBatchSummaryResponse"];
                };
            };
        };
    };
    createBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminBatchSummaryResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBookResponse"];
                };
            };
        };
    };
    getPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListSubscriptionPlanResponse"];
                };
            };
        };
    };
    getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSubscriptionResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListNotificationResponse"];
                };
            };
        };
    };
    unreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringLong"];
                };
            };
        };
    };
    getTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTestForLearnerResponse"];
                };
            };
        };
    };
    myEnrollments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListEnrollmentResponse"];
                };
            };
        };
    };
    myCertificates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCertificateResponse"];
                };
            };
        };
    };
    myBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListBookingResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                track?: "MONEY_FOUNDATIONS" | "EQUITIES" | "BONDS_FIXED_INCOME" | "DERIVATIVES" | "PORTFOLIO_RISK";
                level?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
                language?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseCourseSummaryResponse"];
                };
            };
        };
    };
    getBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCourseDetailResponse"];
                };
            };
        };
    };
    listTests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTestListItemResponse"];
                };
            };
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCourseProgressResponse"];
                };
            };
        };
    };
    listBatches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListBatchForLearnerResponse"];
                };
            };
        };
    };
    verifyCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serial: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCertificateVerifyResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                search?: string;
                category?: string;
                genre?: string;
                language?: string;
                available?: boolean;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseBookResponse"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBookResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAdminUserResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAdminLoanResponse"];
                };
            };
        };
    };
    getTest_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminTestDetailResponse"];
                };
            };
        };
    };
    getBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminBatchDetailResponse"];
                };
            };
        };
    };
    getAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminAnalyticsResponse"];
                };
            };
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
