/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile */
        get: operations["getById"];
        /** Update user profile */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Return a borrowed book */
        put: operations["returnBook"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a book */
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe to a plan */
        post: operations["subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's orders */
        get: operations["getUserOrders"];
        put?: never;
        /** Create an order */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's loans */
        get: operations["getUserLoans"];
        put?: never;
        /** Borrow a book */
        post: operations["borrow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (client should discard tokens) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and get JWT tokens */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new book */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available subscription plans */
        get: operations["getPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user subscription */
        get: operations["getCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all books with optional filters */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a book by ID */
        get: operations["getById_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserRequest: {
            firstName?: string;
            lastName?: string;
            phone?: string;
            address?: string;
        };
        ApiResponseUserResponse: {
            success?: boolean;
            data?: components["schemas"]["UserResponse"];
            message?: string;
            error?: string;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            name?: string;
            role?: string;
            phone?: string;
            address?: string;
        };
        ApiResponseLoanResponse: {
            success?: boolean;
            data?: components["schemas"]["LoanResponse"];
            message?: string;
            error?: string;
        };
        LoanResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            bookId?: string;
            bookTitle?: string;
            bookAuthor?: string;
            bookCover?: string;
            /** Format: date-time */
            borrowedAt?: string;
            /** Format: date-time */
            dueDate?: string;
            /** Format: date-time */
            returnedAt?: string;
            status?: string;
        };
        BookRequest: {
            title: string;
            author: string;
            isbn: string;
            description?: string;
            /** Format: int32 */
            totalCopies?: number;
            purchasePrice: number;
            category?: string;
            language?: string;
            /** Format: int32 */
            pageCount?: number;
            /** Format: double */
            rating?: number;
            coverUrl?: string;
            /** Format: int32 */
            publishedYear?: number;
        };
        ApiResponseBookResponse: {
            success?: boolean;
            data?: components["schemas"]["BookResponse"];
            message?: string;
            error?: string;
        };
        BookResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            author?: string;
            isbn?: string;
            description?: string;
            /** Format: int32 */
            totalCopies?: number;
            /** Format: int32 */
            availableCopies?: number;
            available?: boolean;
            purchasePrice?: number;
            category?: string;
            genre?: string;
            language?: string;
            /** Format: int32 */
            pageCount?: number;
            /** Format: double */
            rating?: number;
            cover?: string;
            /** Format: int32 */
            publishedYear?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        SubscriptionRequest: {
            /** @enum {string} */
            plan: "BASIC" | "PREMIUM" | "ADMIN";
        };
        ApiResponseSubscriptionResponse: {
            success?: boolean;
            data?: components["schemas"]["SubscriptionResponse"];
            message?: string;
            error?: string;
        };
        SubscriptionResponse: {
            /** Format: uuid */
            id?: string;
            plan?: string;
            monthlyPrice?: number;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            status?: string;
            /** Format: int32 */
            maxConcurrentLoans?: number;
        };
        OrderRequest: {
            totalAmount: number;
            notes?: string;
        };
        ApiResponseOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["OrderResponse"];
            message?: string;
            error?: string;
        };
        OrderResponse: {
            /** Format: uuid */
            id?: string;
            totalAmount?: number;
            status?: string;
            notes?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        LoanRequest: {
            /** Format: uuid */
            bookId: string;
            /** Format: int32 */
            daysToKeep?: number;
        };
        RegisterRequest: {
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            phone?: string;
            address?: string;
        };
        ApiResponseAuthResponse: {
            success?: boolean;
            data?: components["schemas"]["AuthResponse"];
            message?: string;
            error?: string;
        };
        AuthResponse: {
            /** Format: uuid */
            userId?: string;
            email?: string;
            name?: string;
            role?: string;
            plan?: string;
            accessToken?: string;
            refreshToken?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            data?: Record<string, never>;
            message?: string;
            error?: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        ApiResponseListSubscriptionPlanResponse: {
            success?: boolean;
            data?: components["schemas"]["SubscriptionPlanResponse"][];
            message?: string;
            error?: string;
        };
        SubscriptionPlanResponse: {
            id?: string;
            name?: string;
            price?: number;
            /** Format: int32 */
            maxBooks?: number;
            features?: string[];
            popular?: boolean;
        };
        ApiResponseListOrderResponse: {
            success?: boolean;
            data?: components["schemas"]["OrderResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponseListLoanResponse: {
            success?: boolean;
            data?: components["schemas"]["LoanResponse"][];
            message?: string;
            error?: string;
        };
        ApiResponsePagedResponseBookResponse: {
            success?: boolean;
            data?: components["schemas"]["PagedResponseBookResponse"];
            message?: string;
            error?: string;
        };
        PagedResponseBookResponse: {
            content?: components["schemas"]["BookResponse"][];
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            hasNext?: boolean;
            hasPrev?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    returnBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoanResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBookResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSubscriptionResponse"];
                };
            };
        };
    };
    getUserOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListOrderResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponse"];
                };
            };
        };
    };
    getUserLoans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListLoanResponse"];
                };
            };
        };
    };
    borrow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoanResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBookResponse"];
                };
            };
        };
    };
    getPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListSubscriptionPlanResponse"];
                };
            };
        };
    };
    getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSubscriptionResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                search?: string;
                category?: string;
                genre?: string;
                language?: string;
                available?: boolean;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseBookResponse"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBookResponse"];
                };
            };
        };
    };
}
